### PR TITLE
Update recipe feature implemented

### PR DESCRIPTION
**Pull request by melanie-bartolome**
Users can update their recipe by entering an ID to modify other details. Have tested this feature.

### CODE REVIEW

**Comment by melanie-bartolome** [comment]
1 conflict in index.js and 1 conflict in index.html. Resolve these conflicts first to merge.

**Comment by melanie-bartolome** [comment]
Modifying codes in backend (index.js)

**Comment by jan311etan** [comment]
codes look good, proceed to merge

**Comment by 2302538J** [comment]
codes look good can proceed

**Comment by yuj1e1** [comment]
codes look good, can proceed :)

**Pull request merged**
